# vim:ft=kitty
## name: Nord
## author: Eric N. Vander Weele
## upstream: https://www.nordtheme.com/
## blurb: Nord theme utilizing the full Frost and Aurora palette.

# Basic colors
foreground           #d8dee9
background           #191D24
selection_foreground #d8dee9
selection_background #434c5e

# Cursor colors
cursor            #d8dee9
cursor_text_color #3b4252

# URL underline color when hovering with mouse
url_color #0087bd

# Window border colors and terminal bell colors
active_border_color   #81a1c1
inactive_border_color #4c566a
bell_border_color     #88c0d0
visual_bell_color     none

# Tab bar colors
active_tab_foreground   #3b4252
active_tab_background   #88c0d0
inactive_tab_foreground #e5e9f0
inactive_tab_background #4c566a
tab_bar_background      #3b4252
tab_bar_margin_color    none

# Mark colors (marked text in the terminal)
mark1_foreground #3b4252
mark1_background #88c0d0
mark2_foreground #3b4252
mark2_background #bf616a
mark3_foreground #3b4252
mark3_background #ebcb8b

# The basic 16 colors
# black
color0 #242933
color8 #2e3440

# red
color1 #b74e58
color9 #b74e58

# green
color2  #97b67c
color10 #97b67c

# yellow
color3  #e7c173
color11 #e7c173

# blue
color4  #5e81ac
color12 #5e81ac

# magenta
color5  #a97ea1
color13 #a97ea1

# cyan
color6  #80b3b2
color14 #80b3b2

# white
color7  #eceff4
color15 #eceff4
