general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on display after wake
}

# 1. DIM SCREEN (Visual Warning)
listener {
    timeout = 300                                # 5 minutes
    on-timeout = brightnessctl set 10%           # set monitor backlight to 10%
    on-resume = brightnessctl set 100%           # restore monitor backlight
}

# 2. LOCK SCREEN
listener {
    timeout = 600                                # 10 minutes
    on-timeout = loginctl lock-session           # lock screen
}

# 3. TURN OFF DISPLAY (Power Save)
listener {
    timeout = 600                                # 10 minutes
    on-timeout = hyprctl dispatch dpms off       # turn off screen
    on-resume = hyprctl dispatch dpms on         # turn on screen
}

# 4. SUSPEND
listener {
    timeout = 1800                               # 30 minutes
    on-timeout = systemctl suspend               # suspend pc
}
